### ISSUE TITLE
Add example code for MPU6050

### ISSUE THREAD

**Issue by VedantParanjape** [SRA-VJTI/sra-board-examples#5]
It should simply print the values from accelerometer using ESP_LOGI

Refer to this example: https://github.com/SRA-VJTI/sra-board-examples/blob/main/bar_graph/main/main.c

**Comment by laukik-hase** [comment]
An example code printing the raw values of the MPU is required, correct?

**Comment by VedantParanjape** [comment]
Yes, correct. Just to let the user know how to use this library.
